[package]
name = "bellman_ford"
version = "0.1.0"
authors = ["Yohei Osawa <yohei.osawa.318.niko8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input = {path = "../../library/input"}